OSC/phylogatr-web

.gitlab-ci.yml

also tag the latest image

---

.rubocop.yml

add rubocop

---

genes.rb

ensure relative file paths because this was failing for me trying to write to the root directory.

ensure relative file paths

---

submit_pipeline.sh

use sbatch files in submit script

use sbatch files in submit script

---

Gemfile
config/database.yml

need gdbm gem and quotes on db strings

need gdbm gem and quotes on db strings

---

.gitignore
align.sbatch
align_sequences.sh
app/models/bold_record.rb
docs/PIPELINE.md
env
lib/tasks/metrics.rake
lib/tasks/pipeline.rake

updates mostly for alignments. This also adds 1 metric collection task for looking at Bold records.

updates for alignment and metric collection

---

.rubocop.yml

rm rspec bits from rubocop

---

align_sequences.sh
lib/tasks/pipeline.rake
submit_pipeline.sh

Just some alignment updates I had to do as I worked through it.

some alignment updates

---

app/models/gbif_genbank_linker.rb
app/models/pipeline_metrics.rb
link_gbif_with_genbank.sbatch

save metrics for the `link_gbif_with_genbank.sbatch` file.
This will now generate 
* gbif_expand_occurrences_on_accession
* link_occurrence_and_genes

save metrics for link_gbif_with_genbank

---

app/models/bold_record.rb
app/models/pipeline_metrics.rb
filter_bold_records.sbatch
lib/tasks/metrics.rake
lib/tasks/pipeline.rake
populate_database.sbatch

add bold records and commits the metrics:save_record task

---

add_bold_records.sbatch
lib/tasks/pipeline.rake

Collect metrics for adding bold records.

adding bold records records metrics

---

.github/workflows/release.yml
.zenodo.json

add a zenodo release action. 
This is the DOI for this project.
https://doi.org/10.5281/zenodo.6342132

add a zenodo release action

---

.github/workflows/release.yml

fix zenodo release

---

app/controllers/ping_controller.rb
config/routes.rb

add a ping controller for kuberentes health checks.

add a ping controller

---

app/models/batch_search_results.rb

-D option needs to be a string

---

config/initializers/open3_extensions.rb

Add an initializer to log slurm commands.

add initer to log slurm commands

---

Dockerfile
app/controllers/application_controller.rb
app/views/application/_maintenance.html.erb

Put the app in maintenance mode until we can update to a newer cluster.

Maintenance mode

---

.github/workflows/release.yml

update zenodo workflow

---

Dockerfile

update dockerfile with higher ruby version

update dockerfile with higher ruby version

---

Dockerfile

still trying to fix the build.

add gdbm-devel to packages

---

Dockerfile
Gemfile
Gemfile.lock

attempt to fix the container
